## THIS FILE IS AUTOGENERATED! DO NOT EDIT! ##
# Puppet manifest
# Configuration: {{ general['template'] }}
# Nodes: {{ nodes|count }}
#
# Networks:
# External: {{ networks['external'] }}
# Management: {{ networks['management'] }}
# Private: {{ networks['private'] }}
#

